In [5]:
import pandas as pd #as keyword is used to define an alias

url = "https://raw.githubusercontent.com/braincomputingsantosh/Data/master/chipotle.tsv.txt"
chipoDF = pd.read_csv(url, sep='\t') #t=tab 

chipoDF

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [7]:
#reassign column with cleaned item prices

# Chipotle Dataframes

In [10]:
#delete the duplicates in item_name and quantity
chipoDF_filtered = chipoDF.drop_duplicates(['item_name', 'quantity'])
chipoDF_filtered

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
3890,1559,2,Carnitas Crispy Tacos,"[Fresh Tomato Salsa (Mild), [Cheese, Lettuce]]",$17.98
3973,1592,4,Canned Soft Drink,[Coke],$5.00
4152,1660,10,Bottled Water,NaN,$15.00
4354,1738,2,Steak Soft Tacos,"[Fresh Tomato Salsa, [Cheese, Lettuce]]",$18.50
4489,1786,4,Chips and Guacamole,NaN,$17.80

In [11]:
#clean the items_price column and trnasform it in a float
prices = [float(value[1:-1]) for value in chipoDF.item_price]
prices

[2.39,
 3.39,
 3.39,
 2.39,
 16.98,
 10.98,
 1.69,
 11.75,
 9.25,
 9.25,
 4.45,
 8.75,
 8.75,
 11.25,
 4.45,
 2.39,
 8.49,
 8.49,
 2.18,
 8.75,
 4.45,
 8.99,
 3.39,
 10.98,
 3.39,
 2.39,
 8.49,
 8.99,
 1.09,
 8.49,
 2.39,
 8.99,
 1.69,
 8.99,
 1.09,
 8.75,
 8.75,
 4.45,
 2.95,
 11.75,
 2.15,
 4.45,
 11.25,
 11.75,
 8.75,
 10.98,
 8.99,
 3.39,
 8.99,
 3.99,
 8.99,
 2.18,
 10.98,
 1.09,
 8.99,
 2.39,
 9.25,
 11.25,
 11.75,
 2.15,
 4.45,
 9.25,
 11.25,
 8.75,
 8.99,
 8.99,
 3.39,
 8.99,
 10.98,
 8.99,
 1.69,
 8.99,
 3.99,
 8.75,
 4.45,
 8.75,
 8.75,
 2.15,
 8.75,
 11.25,
 2.15,
 9.25,
 8.75,
 8.75,
 9.25,
 8.49,
 8.99,
 1.09,
 9.25,
 2.95,
 11.75,
 11.75,
 9.25,
 11.75,
 4.45,
 9.25,
 4.45,
 11.75,
 8.75,
 8.75,
 4.45,
 8.99,
 8.99,
 3.99,
 8.49,
 3.39,
 8.99,
 1.09,
 9.25,
 4.45,
 8.75,
 2.95,
 4.45,
 2.39,
 8.49,
 8.99,
 8.49,
 1.09,
 8.99,
 3.99,
 8.75,
 9.25,
 4.45,
 11.25,
 4.45,
 8.99,
 1.09,
 9.25,
 2.95,
 4.45,
 11.75,
 4.45,
 8.49,
 2.39,
 10.98,
 22.5,
 11.75,
 4.45,
 11.25,
 4.45,
 11.25,
 4.45,
 11.25,
 11.25,
 11.75,
 9.25,
 4.45,
 11.48,
 17.98,
 1.69,
 17.5,
 4.45,
 8.49,
 2.39,
 17.5,
 4.45,
 4.45,
 11.25,
 11.75,
 10.98,
 8.49,
 10.98,
 2.18,
 11.48,
 8.49,
 2.39,
 4.45,
 11.25,
 11.75,
 8.75,
 8.49,
 2.18,
 8.49,
 3.39,
 8.49,
 8.99,
 10.98,
 11.48,
 8.49,
 1.09,
 1.09,
 9.25,
 8.75,
 2.95,
 9.25,
 4.45,
 11.25,
 11.48,
 8.49,
 8.49,
 8.99,
 2.39,
 11.25,
 8.75,
 2.95,
 1.09,
 8.99,
 8.49,
 2.39,
 10.98,
 1.09,
 3.99,
 11.25,
 8.75,
 8.49,
 3.39,
 8.75,
 9.25,
 2.15,
 11.25,
 11.25,
 11.25,
 4.45,
 22.5,
 4.45,
 11.75,
 8.75,
 17.5,
 8.75,
 9.25,
 8.75,
 2.15,
 9.25,
 4.3,
 8.75,
 11.25,
 2.15,
 8.99,
 1.09,
 8.99,
 3.99,
 8.75,
 2.95,
 2.95,
 11.75,
 5.9,
 9.25,
 9.25,
 11.75,
 9.25,
 2.95,
 17.5,
 8.75,
 9.25,
 10.98,
 8.99,
 1.09,
 1.09,
 1.09,
 8.99,
 10.98,
 1.09,
 8.75,
 8.75,
 9.25,
 9.25,
 8.75,
 8.75,
 8.99,
 8.99,
 8.99,
 1.09,
 11.75,
 1.25,
 8.99,
 2.39,
 9.25,
 2.95,
 8.99,
 3.99,
 8.49,
 2.39,
 8.49,
 8.49,
 8.49,
 1.69,
 8.49,
 3.99,
 8.99,
 1.69,
 1.09,
 23.78,
 17.5,
 2.15,
 8.75,
 9.25,
 9.25,
 8.75,
 4.45,
 8.75,
 11.25,
 11.25,
 1.25,
 9.25,
 4.45,
 11.25,
 11.75,
 11.75,
 6.49,
 8.99,
 2.39,
 8.49,
 2.39,
 11.25,
 8.75,
 2.15,
 8.99,
 1.69,
 8.75,
 11.25,
 2.15,
 4.45,
 8.75,
 8.49,
 8.99,
 17.5,
 8.49,
 1.09,
 1.09,
 8.75,
 1.25,
 2.15,
 11.08,
 8.49,
 8.49,
 8.99,
 2.39,
 8.75,
 2.15,
 1.5,
 11.25,
 2.15,
 8.49,
 8.49,
 11.75,
 9.25,
 11.75,
 1.25,
 11.25,
 8.75,
 4.45,
 6.49,
 9.25,
 2.95,
 11.25,
 4.45,
 1.25,
 1.25,
 8.49,
 2.39,
 2.18,
 8.49,
 2.18,
 22.16,
 17.5,
 8.75,
 2.95,
 6.49,
 8.99,
 3.39,
 3.39,
 8.99,
 8.49,
 11.25,
 2.15,
 11.25,
 2.95,
 11.25,
 1.25,
 8.99,
 1.09,
 8.75,
 8.75,
 9.25,
 2.95,
 11.75,
 1.5,
 8.99,
 1.09,
 11.25,
 1.25,
 1.25,
 11.25,
 11.75,
 2.15,
 8.99,
 1.69,
 11.75,
 6.49,
 8.75,
 9.25,
 11.25,
 4.45,
 1.25,
 11.25,
 4.45,
 8.49,
 8.99,
 8.49,
 8.99,
 11.25,
 1.25,
 11.75,
 1.25,
 11.75,
 9.25,
 4.45,
 11.25,
 2.15,
 32.94,
 1.25,
 11.25,
 11.48,
 1.69,
 1.09,
 17.5,
 4.45,
 6.49,
 9.25,
 8.75,
 9.25,
 9.25,
 8.75,
 8.75,
 2.15,
 2.95,
 17.5,
 10.98,
 11.48,
 11.48,
 3.39,
 8.99,
 1.69,
 8.99,
 1.09,
 10.98,
 3.39,
 8.99,
 1.09,
 9.25,
 8.75,
 11.25,
 4.45,
 2.95,
 9.25,
 22.2,
 8.49,
 8.99,
 8.75,
 8.75,
 11.75,
 8.75,
 11.25,
 9.25,
 11.25,
 11.25,
 8.75,
 11.25,
 2.95,
 1.25,
 8.49,
 1.69,
 11.75,
 11.25,
 8.75,
 8.75,
 4.45,
 8.49,
 3.99,
 8.49,
 3.99,
 11.48,
 1.69,
 1.09,
 11.25,
 1.5,
 10.58,
 1.69,
 9.25,
 11.25,
 8.75,
 9.25,
 11.25,
 11.25,
 8.75,
 11.75,
 8.75,
 8.75,
 8.75,
 2.15,
 11.25,
 11.75,
 2.5,
 4.45,
 9.25,
 4.45,
 11.25,
 8.49,
 3.99,
 9.25,
 9.25,
 11.25,
 9.25,
 11.75,
 11.25,
 1.25,
 23.5,
 1.25,
 8.99,
 8.49,
 7.4,
 7.4,
 8.75,
 1.25,
 4.45,
 8.75,
 2.15,
 8.75,
 4.45,
 7.4,
 7.4,
 7.4,
 8.99,
 3.99,
 8.99,
 1.69,
 8.75,
 8.75,
 8.75,
 8.75,
 11.25,
 11.25,
 2.95,
 8.75,
 18.5,
 8.49,
 3.99,
 2.95,
 9.25,
 9.25,
 3.0,
 1.25,
 8.75,
 9.25,
 4.45,
 8.75,
 11.25,
 4.45,
 10.98,
 22.16,
 4.45,
 8.75,
 9.25,
 6.49,
 9.25,
 11.25,
 8.75,
 9.25,
 2.15,
 9.25,
 4.45,
 9.25,
 2.95,
 9.25,
 8.75,
 9.25,
 1.25,
 1.25,
 8.75,
 8.75,
 9.25,
 4.45,
 11.75,
 11.75,
 11.75,
 9.25,
 9.25,
 16.98,
 2.39,
 3.39,
 3.39,
 9.25,
 11.75,
 11.25,
 2.15,
 8.75,
 9.25,
 4.45,
 10.98,
 11.25,
 9.25,
 22.5,
 9.25,
 2.95,
 1.5,
 11.48,
 8.49,
 1.69,
 8.49,
 8.49,
 8.49,
 6.78,
 11.75,
 4.45,
 8.75,
 4.45,
 11.89,
 9.39,
 8.75,
 2.95,
 1.25,
 9.25,
 8.75,
 23.78,
 8.75,
 9.25,
 2.15,
 2.15,
 1.25,
 8.49,
 3.99,
 10.98,
 1.09,
 8.75,
 4.45,
 8.75,
 11.75,
 2.95,
 4.45,
 9.25,
 8.75,
 8.49,
 3.99,
 22.5,
 11.25,
 1.25,
 8.75,
 8.75,
 18.5,
 6.49,
 8.75,
 8.75,
 4.45,
 8.49,
 3.99,
 8.99,
 1.09,
 8.49,
 2.39,
 11.48,
 1.69,
 2.5,
 9.25,
 1.5,
 17.5,
 2.95,
 8.75,
 4.45,
 11.75,
 8.75,
 8.49,
 1.69,
 8.49,
 3.99,
 8.99,
 8.99,
 3.99,
 8.99,
 11.25,
 4.45,
 1.25,
 3.99,
 10.98,
 7.4,
 3.0,
 7.4,
 4.0,
 8.49,
 3.99,
 9.25,
 4.45,
 11.25,
 1.25,
 11.75,
 1.25,
 11.25,
 2.15,
 11.25,
 4.45,
 3.75,
 11.75,
 8.99,
 2.39,
 8.75,
 4.45,
 1.25,
 8.99,
 8.49,
 2.18,
 8.49,
 2.18,
 1.09,
 8.75,
 2.95,
 1.25,
 1.5,
 11.25,
 9.25,
 2.95,
 1.25,
 8.49,
 3.99,
 11.48,
 3.99,
 8.49,
 11.25,
 1.25,
 8.99,
 1.69,
 11.25,
 1.25,
 6.49,
 8.75,
 9.25,
 8.75,
 2.95,
 8.75,
 11.75,
 8.69,
 8.69,
 2.29,
 3.99,
 8.49,
 8.75,
 8.75,
 1.25,
 11.75,
 11.25,
 11.25,
 11.25,
 1.25,
 9.25,
 11.75,
 6.49,
 3.99,
 8.49,
 11.25,
 2.15,
 11.25,
 11.89,
 8.99,
 1.69,
 8.99,
 8.99,
 3.99,
 8.99,
 9.25,
 9.25,
 2.15,
 7.4,
 7.4,
 8.75,
 8.75,
 9.25,
 4.45,
 11.25,
 1.25,
 11.75,
 11.25,
 1.25,
 3.99,
 8.49,
 8.49,
 8.49,
 8.99,
 8.75,
 2.15,
 1.25,
 8.49,
 1.09,
 1.09,
 8.75,
 2.95,
 1.25,
 9.25,
 1.25,
 2.15,
 11.25,
 1.25,
 4.45,
 8.75,
 2.5,
 8.9,
 8.75,
 8.75,
 8.75,
 11.25,
 11.25,
 10.98,
 3.99,
 10.98,
 3.99,
 1.69,
 8.99,
 9.25,
 8.75,
 8.99,
 1.09,
 9.25,
 2.95,
 8.75,
 9.25,
 3.99,
 8.49,
 8.75,
 8.75,
 22.5,
 10.98,
 3.27,
 3.99,
 8.99,
 1.09,
 11.08,
 8.75,
 4.45,
 11.08,
 3.99,
 8.49,
 4.3,
 9.25,
 8.75,
 11.25,
 11.25,
 9.25,
 8.49,
 8.99,
 8.49,
 8.75,
 2.95,
 4.45,
 9.25,
 2.95,
 9.25,
 8.75,
 11.25,
 4.45,
 16.98,
 8.49,
 2.39,
 11.25,
 3.75,
 9.25,
 4.45,
 9.25,
 9.25,
 4.45,
 8.75,
 9.25,
 8.75,
 9.25,
 9.25,
 9.25,
 11.48,
 8.99,
 22.5,
 11.75,
 11.25,
 1.25,
 8.75,
 2.15,
 1.25,
 11.25,
 8.75,
 1.25,
 11.25,
 1.5,
 11.25,
 11.25,
 9.25,
 6.49,
 8.9,
 8.75,
 4.45,
 11.25,
 1.25,
 17.5,
 9.25,
 8.75,
 11.75,
 3.0,
 8.49,
 8.49,
 10.98,
 8.99,
 3.99,
 8.75,
 4.45,
 8.99,
 1.69,
 11.75,
 8.75,
 11.25,
 4.45,
 11.75,
 1.25,
 11.75,
 2.95,
 8.99,
 8.99,
 2.18,
 17.98,
 8.99,
 8.49,
 1.69,
 11.75,
 11.25,
 2.95,
 3.75,
 9.25,
 11.75,
 8.75,
 2.15,
 1.5,
 8.49,
 8.49,
 3.39,
 8.69,
 3.89,
 8.75,
 4.45,
 8.75,
 11.25,
 2.15,
 8.75,
 8.49,
 1.69,
 8.49,
 8.49,
 1.25,
 8.75,
 11.75,
 11.75,
 8.99,
 1.09,
 8.75,
 4.45,
 8.75,
 2.95,
 8.75,
 2.15,
 3.99,
 8.49,
 8.99,
 3.99,
 8.49,
 1.69,
 1.09,
 8.99,
 1.09,
 9.25,
 8.75,
 8.99,
 2.39,
 1.25,
 1.25,
 11.25,
 11.25,
 9.25,
 9.25,
 11.25,
 1.5,
 3.99,
 8.49,
 11.25,
 9.25,
 11.25,
 17.5,
 8.75,
 8.9,
 8.75,
 8.75,
 8.99,
 2.39,
 11.25,
 9.25,
 2.15,
 11.25,
 1.25,
 11.75,
 1.25,
 11.25,
 11.75,
 1.25,
 11.25,
 11.25,
 8.49,
 10.98,
 8.75,
 1.25,
 8.75,
 ...]

In [12]:
chipoDF.item_price = prices

In [13]:
#select only the products with quantity equals to 1
chipoDF_one_product = chipoDF_filtered[chipoDF_filtered.quantity == 1]
chipoDF_one_product

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$8.99
27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.99
28,14,1,Canned Soda,[Dr. Pepper],$1.09
33,17,1,Carnitas Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99
34,17,1,Bottled Water,NaN,$1.09
38,18,1,Chips and Tomatillo Green Chili Salsa,NaN,$2.95
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$11.75
40,19,1,Chips,NaN,$2.15
44,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75
54,25,1,Steak Bowl,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.99
56,26,1,Barbacoa Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",$9.25
57,26,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25
62,28,1,Veggie Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
92,40,1,Steak Crispy Tacos,"[Fresh Tomato Salsa, Sour Cream]",$9.25
111,49,1,Chips and Tomatillo Red Chili Salsa,NaN,$2.95
168,75,1,Barbacoa Crispy Tacos,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$11.75
186,83,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
191,85,1,Chips and Roasted Chili-Corn Salsa,NaN,$2.39
233,102,1,Chips and Roasted Chili Corn Salsa,NaN,$2.95
237,103,1,Carnitas Soft Tacos,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$9.25
250,109,1,Chicken Salad,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$10.98
263,114,1,Canned Soft Drink,[Coke],$1.25
298,129,1,6 Pack Soft Drink,[Sprite],$6.49
300,130,1,Chips and Tomatillo-Red Chili Salsa,NaN,$2.39
510,214,1,Burrito,"[Adobo-Marinated and Grilled Chicken, Pinto Be...",$7.40
520,217,1,Crispy Tacos,[Adobo-Marinated and Grilled Steak],$7.40
554,230,1,Carnitas Crispy Tacos,[Roasted Chili Corn Salsa],$9.25
606,250,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Pinto Beans, Cheese, Gua...",$11.89
664,276,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99
673,279,1,Bowl,"[Adobo-Marinated and Grilled Steak, [Sour Crea...",$7.40
674,279,1,Chips and Mild Fresh Tomato Salsa,NaN,$3.00
738,304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25
1132,468,1,Carnitas Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.89
1229,501,1,Barbacoa Salad Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",$11.89
1414,575,1,Salad,"[Brown Rice, Adobo-Marinated and Grilled Chick...",$7.40
1653,668,1,Veggie Crispy Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",$8.49
1694,686,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.49
3750,1500,1,Carnitas Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.99

In [17]:
chipoDF_one_product[chipoDF_one_product['item_price']<10].item_name.nunique()

38

In [15]:
#what is the price of each time?
# orient data frame with only 2 columns, item_name and item_price

chipoDF_filtered = chipoDF.drop_duplicates(['item_name', 'quantity'])
#select only the products with quantity equals 1
chipoDF_one_product = chipoDF_filtered[chipoDF_filtered.quantity == 1]
#Select only the item_name an item_price columns
price_per_item = chipoDF_one_product[['item_name', 'item_price']]
#sort the values from the most to less expensive
price_per_item.sort_values(by=["item_name", "item_price"], ascending=[True, False])#.head(10)

                                  item_name  item_price
298                       6 Pack Soft Drink        6.49
39                            Barbacoa Bowl       11.75
21                         Barbacoa Burrito        8.99
168                   Barbacoa Crispy Tacos       11.75
1229                    Barbacoa Salad Bowl       11.89
56                      Barbacoa Soft Tacos        9.25
34                            Bottled Water        1.09
673                                    Bowl        7.40
510                                 Burrito        7.40
28                              Canned Soda        1.09
263                       Canned Soft Drink        1.25
33                            Carnitas Bowl        8.99
27                         Carnitas Burrito        8.99
554                   Carnitas Crispy Tacos        9.25
3750                         Carnitas Salad        8.99
1132                    Carnitas Salad Bowl       11.89
237                     Carnitas Soft Tacos        9.25
5                              Chicken Bowl       10.98
16                          Chicken Burrito        8.49
11                     Chicken Crispy Tacos        8.75
250                           Chicken Salad       10.98
44                       Chicken Salad Bowl        8.75
12                       Chicken Soft Tacos        8.75
40                                    Chips        2.15
0              Chips and Fresh Tomato Salsa        2.39
10                      Chips and Guacamole        4.45
674       Chips and Mild Fresh Tomato Salsa        3.00
233      Chips and Roasted Chili Corn Salsa        2.95
191      Chips and Roasted Chili-Corn Salsa        2.39
38    Chips and Tomatillo Green Chili Salsa        2.95
111     Chips and Tomatillo Red Chili Salsa        2.95
3     Chips and Tomatillo-Green Chili Salsa        2.39
300     Chips and Tomatillo-Red Chili Salsa        2.39
520                            Crispy Tacos        7.40
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
1414                                  Salad        7.40
6                             Side of Chips        1.69
54                               Steak Bowl        8.99
7                             Steak Burrito       11.75
92                       Steak Crispy Tacos        9.25
664                             Steak Salad        8.99
606                        Steak Salad Bowl       11.89
8                          Steak Soft Tacos        9.25
62                              Veggie Bowl       11.25
57                           Veggie Burrito       11.25
1653                    Veggie Crispy Tacos        8.49
1694                           Veggie Salad        8.49
186                       Veggie Salad Bowl       11.25
738                       Veggie Soft Tacos       11.25

In [18]:
# Sort by the name of the item
chipoDF.sort_values(by = "item_name")

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

In [25]:
#what was the quantity of the most expensive item ordered
chipoDF.sort_values(by ="item_name", ascending=False).head(1)

,order_id,quantity,item_name,choice_description,item_price
3889,1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98